version: "3.8"

services:
  core:
    build:
      args:
        - BASE_IMAGE=ubuntu:20.04
        - PYTHON_VERSION=3.8
        - UID=1000
        - GID=1000
      context: ../../
      dockerfile: environments/Dockerfile
    tty: true
    volumes:
        - ../../:/home/challenger/ascender
    ports:
        - 8000:8000