_target_: neddf.network.NeDDF
embed_pos_rank: 10
embed_dir_rank: 4
ddf_layer_count: 8
ddf_layer_width: 256
col_layer_count: 4
col_layer_width: 256
d_near: 0.001
activation_type: "tanhExp"
lowpass_alpha_offset: 6
penalty_weight:
  constraints_aux_grad: 0.05
  constraints_dDdt: 1.0
  constraints_color: 0.0001
  range_distance: 1.0
  range_aux_grad: 1.0
  range_color: 0.1
skips:
  - 4