name: tests
on: [pull_request]

env:
  DOCKER_COMPOSE_DIRECTORY: environments/cpu
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1

jobs:
  lint-and-test:
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.image }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        python-version: ["3.8", "3.9"]
        include:
          - os: ubuntu
            image: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: pwd && docker-compose --version && docker --version

      - name: Build docker image
        run: docker-compose build --parallel --build-arg PYTHON_VERSION=${{ matrix.python-version }} core
        working-directory: ${{ env.DOCKER_COMPOSE_DIRECTORY }}

      - name: Start docker container
        run: docker-compose up -d core
        working-directory: ${{ env.DOCKER_COMPOSE_DIRECTORY }}

      # pytest-cov export coverage data to a file
      # However, the directory made by actions/checkout does not allow write
      # chmod is needed to resolve above problem
      - name: Change permission
        run: chmod 777 .

      - name: Install dependencies
        run: docker-compose exec -T core poetry install --no-interaction
        working-directory: ${{ env.DOCKER_COMPOSE_DIRECTORY }}

      - name: Run lint
        run: docker-compose exec -T core make lint
        working-directory: ${{ env.DOCKER_COMPOSE_DIRECTORY }}

      - name: Run test code
        run: docker-compose exec -T core make test
        working-directory: ${{ env.DOCKER_COMPOSE_DIRECTORY }}